app = 'api-dawn-cloud-1945'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[guest]
  cpus = 4  # Set the number of CPUs
  memory_mb = 2048  # Set the memory to 1024 MB (1 GB) or any appropriate value
  gpus = 1  # Number of GPUs to allocate
  gpu_kind = "l40s"  # Specify the GPU typ