app = "api-dawn-cloud-1945"
primary_region = "lax"
# vm.size = "a100-40gb"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[guest]
  cpus = 4  # Number of CPUs allocated to the guest container
  memory_mb = 16384  # 16 GB of memory
  #gpus = 1  # Number of GPUs allocated to the guest
  #gpu_kind = "l40s"  # GPU type for the guest

